// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ResponseStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/response-status-code.js';


export class AnswerFriendshipResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AnswerFriendshipResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAnswerFriendshipResponse(bb:flatbuffers.ByteBuffer, obj?:AnswerFriendshipResponse):AnswerFriendshipResponse {
  return (obj || new AnswerFriendshipResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAnswerFriendshipResponse(bb:flatbuffers.ByteBuffer, obj?:AnswerFriendshipResponse):AnswerFriendshipResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AnswerFriendshipResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

approved():ResponseStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponseStatusCode.Success;
}

static startAnswerFriendshipResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addApproved(builder:flatbuffers.Builder, approved:ResponseStatusCode) {
  builder.addFieldInt8(0, approved, ResponseStatusCode.Success);
}

static endAnswerFriendshipResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAnswerFriendshipResponse(builder:flatbuffers.Builder, approved:ResponseStatusCode):flatbuffers.Offset {
  AnswerFriendshipResponse.startAnswerFriendshipResponse(builder);
  AnswerFriendshipResponse.addApproved(builder, approved);
  return AnswerFriendshipResponse.endAnswerFriendshipResponse(builder);
}
}
