// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ArcheryArenaFailReason {
  None = 0,
  AlreadyEntered = 1,
  AlreadyClaimed = 2,
  EventDeleted = 3,
  LevelNotReached = 4,
  EventNotActive = 5,
  NotInEvent = 6
}
