// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CardInfo } from '../../../../../royal/infrastructure/services/backend/protocol/card-info.js';
import { ChatProfile } from '../../../../../royal/infrastructure/services/backend/protocol/chat-profile.js';
import { SpecialChatProfile } from '../../../../../royal/infrastructure/services/backend/protocol/special-chat-profile.js';


export class AskTeamSeasonalCardCollectionCardRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AskTeamSeasonalCardCollectionCardRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAskTeamSeasonalCardCollectionCardRequest(bb:flatbuffers.ByteBuffer, obj?:AskTeamSeasonalCardCollectionCardRequest):AskTeamSeasonalCardCollectionCardRequest {
  return (obj || new AskTeamSeasonalCardCollectionCardRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAskTeamSeasonalCardCollectionCardRequest(bb:flatbuffers.ByteBuffer, obj?:AskTeamSeasonalCardCollectionCardRequest):AskTeamSeasonalCardCollectionCardRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AskTeamSeasonalCardCollectionCardRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

teamId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

userName():string|null
userName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
userName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

profile(obj?:ChatProfile):ChatProfile|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new ChatProfile()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

specialProfile(obj?:SpecialChatProfile):SpecialChatProfile|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new SpecialChatProfile()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

cardInfo(obj?:CardInfo):CardInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new CardInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startAskTeamSeasonalCardCollectionCardRequest(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addTeamId(builder:flatbuffers.Builder, teamId:bigint) {
  builder.addFieldInt64(0, teamId, BigInt('0'));
}

static addUserName(builder:flatbuffers.Builder, userNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, userNameOffset, 0);
}

static addProfile(builder:flatbuffers.Builder, profileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, profileOffset, 0);
}

static addSpecialProfile(builder:flatbuffers.Builder, specialProfileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, specialProfileOffset, 0);
}

static addCardInfo(builder:flatbuffers.Builder, cardInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, cardInfoOffset, 0);
}

static endAskTeamSeasonalCardCollectionCardRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
