// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ByteArrayKeyType {
  None = 0,
  MagicCauldron = 1,
  SeasonalCardCollection = 2,
  MissionPursuit = 3,
  MissionControl = 4,
  TrainJourney = 5,
  OceanOdyssey = 6,
  PuzzleBreak = 7,
  NewRoyalPass = 8
}
