// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ChatMessageFailReason } from '../../../../../royal/infrastructure/services/backend/protocol/chat-message-fail-reason.js';
import { ResponseStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/response-status-code.js';


export class ChangeUserNameResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChangeUserNameResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChangeUserNameResponse(bb:flatbuffers.ByteBuffer, obj?:ChangeUserNameResponse):ChangeUserNameResponse {
  return (obj || new ChangeUserNameResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChangeUserNameResponse(bb:flatbuffers.ByteBuffer, obj?:ChangeUserNameResponse):ChangeUserNameResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChangeUserNameResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():ResponseStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponseStatusCode.Success;
}

userData():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

failReason():ChatMessageFailReason {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ChatMessageFailReason.None;
}

static startChangeUserNameResponse(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStatus(builder:flatbuffers.Builder, status:ResponseStatusCode) {
  builder.addFieldInt8(0, status, ResponseStatusCode.Success);
}

static addUserData(builder:flatbuffers.Builder, userData:bigint) {
  builder.addFieldInt64(1, userData, BigInt('0'));
}

static addFailReason(builder:flatbuffers.Builder, failReason:ChatMessageFailReason) {
  builder.addFieldInt8(2, failReason, ChatMessageFailReason.None);
}

static endChangeUserNameResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChangeUserNameResponse(builder:flatbuffers.Builder, status:ResponseStatusCode, userData:bigint, failReason:ChatMessageFailReason):flatbuffers.Offset {
  ChangeUserNameResponse.startChangeUserNameResponse(builder);
  ChangeUserNameResponse.addStatus(builder, status);
  ChangeUserNameResponse.addUserData(builder, userData);
  ChangeUserNameResponse.addFailReason(builder, failReason);
  return ChangeUserNameResponse.endChangeUserNameResponse(builder);
}
}
