// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ClaimSpaceMissionRewardResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ClaimSpaceMissionRewardResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClaimSpaceMissionRewardResponse(bb:flatbuffers.ByteBuffer, obj?:ClaimSpaceMissionRewardResponse):ClaimSpaceMissionRewardResponse {
  return (obj || new ClaimSpaceMissionRewardResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClaimSpaceMissionRewardResponse(bb:flatbuffers.ByteBuffer, obj?:ClaimSpaceMissionRewardResponse):ClaimSpaceMissionRewardResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ClaimSpaceMissionRewardResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startClaimSpaceMissionRewardResponse(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endClaimSpaceMissionRewardResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createClaimSpaceMissionRewardResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  ClaimSpaceMissionRewardResponse.startClaimSpaceMissionRewardResponse(builder);
  return ClaimSpaceMissionRewardResponse.endClaimSpaceMissionRewardResponse(builder);
}
}
