// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ClaimWeeklyLeaderboardResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ClaimWeeklyLeaderboardResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClaimWeeklyLeaderboardResponse(bb:flatbuffers.ByteBuffer, obj?:ClaimWeeklyLeaderboardResponse):ClaimWeeklyLeaderboardResponse {
  return (obj || new ClaimWeeklyLeaderboardResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClaimWeeklyLeaderboardResponse(bb:flatbuffers.ByteBuffer, obj?:ClaimWeeklyLeaderboardResponse):ClaimWeeklyLeaderboardResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ClaimWeeklyLeaderboardResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startClaimWeeklyLeaderboardResponse(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endClaimWeeklyLeaderboardResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createClaimWeeklyLeaderboardResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  ClaimWeeklyLeaderboardResponse.startClaimWeeklyLeaderboardResponse(builder);
  return ClaimWeeklyLeaderboardResponse.endClaimWeeklyLeaderboardResponse(builder);
}
}
