// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ResponseStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/response-status-code.js';


export class ConsumeSystemMessagesResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConsumeSystemMessagesResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConsumeSystemMessagesResponse(bb:flatbuffers.ByteBuffer, obj?:ConsumeSystemMessagesResponse):ConsumeSystemMessagesResponse {
  return (obj || new ConsumeSystemMessagesResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConsumeSystemMessagesResponse(bb:flatbuffers.ByteBuffer, obj?:ConsumeSystemMessagesResponse):ConsumeSystemMessagesResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConsumeSystemMessagesResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():ResponseStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponseStatusCode.Success;
}

static startConsumeSystemMessagesResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addStatus(builder:flatbuffers.Builder, status:ResponseStatusCode) {
  builder.addFieldInt8(0, status, ResponseStatusCode.Success);
}

static endConsumeSystemMessagesResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConsumeSystemMessagesResponse(builder:flatbuffers.Builder, status:ResponseStatusCode):flatbuffers.Offset {
  ConsumeSystemMessagesResponse.startConsumeSystemMessagesResponse(builder);
  ConsumeSystemMessagesResponse.addStatus(builder, status);
  return ConsumeSystemMessagesResponse.endConsumeSystemMessagesResponse(builder);
}
}
