// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ConsumeSystemMessagesRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConsumeSystemMessagesRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConsumeSystemMessagesRequest(bb:flatbuffers.ByteBuffer, obj?:ConsumeSystemMessagesRequest):ConsumeSystemMessagesRequest {
  return (obj || new ConsumeSystemMessagesRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConsumeSystemMessagesRequest(bb:flatbuffers.ByteBuffer, obj?:ConsumeSystemMessagesRequest):ConsumeSystemMessagesRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConsumeSystemMessagesRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

messageId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startConsumeSystemMessagesRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMessageId(builder:flatbuffers.Builder, messageId:number) {
  builder.addFieldInt32(0, messageId, 0);
}

static endConsumeSystemMessagesRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConsumeSystemMessagesRequest(builder:flatbuffers.Builder, messageId:number):flatbuffers.Offset {
  ConsumeSystemMessagesRequest.startConsumeSystemMessagesRequest(builder);
  ConsumeSystemMessagesRequest.addMessageId(builder, messageId);
  return ConsumeSystemMessagesRequest.endConsumeSystemMessagesRequest(builder);
}
}
