// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DailyLightningRushGroupInfo } from '../../../../../royal/infrastructure/services/backend/protocol/daily-lightning-rush-group-info.js';
import { DailyLightningRushInfo } from '../../../../../royal/infrastructure/services/backend/protocol/daily-lightning-rush-info.js';


export class DailyLightningRushRefreshInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DailyLightningRushRefreshInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDailyLightningRushRefreshInfo(bb:flatbuffers.ByteBuffer, obj?:DailyLightningRushRefreshInfo):DailyLightningRushRefreshInfo {
  return (obj || new DailyLightningRushRefreshInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDailyLightningRushRefreshInfo(bb:flatbuffers.ByteBuffer, obj?:DailyLightningRushRefreshInfo):DailyLightningRushRefreshInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DailyLightningRushRefreshInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

serverDailyLightningRushInfo(obj?:DailyLightningRushInfo):DailyLightningRushInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DailyLightningRushInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

userDailyLightningRushInfo(obj?:DailyLightningRushInfo):DailyLightningRushInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new DailyLightningRushInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

dailyLightningRushGroupInfo(obj?:DailyLightningRushGroupInfo):DailyLightningRushGroupInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new DailyLightningRushGroupInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startDailyLightningRushRefreshInfo(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addServerDailyLightningRushInfo(builder:flatbuffers.Builder, serverDailyLightningRushInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, serverDailyLightningRushInfoOffset, 0);
}

static addUserDailyLightningRushInfo(builder:flatbuffers.Builder, userDailyLightningRushInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, userDailyLightningRushInfoOffset, 0);
}

static addDailyLightningRushGroupInfo(builder:flatbuffers.Builder, dailyLightningRushGroupInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, dailyLightningRushGroupInfoOffset, 0);
}

static endDailyLightningRushRefreshInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
