// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DeleteUserRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DeleteUserRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDeleteUserRequest(bb:flatbuffers.ByteBuffer, obj?:DeleteUserRequest):DeleteUserRequest {
  return (obj || new DeleteUserRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDeleteUserRequest(bb:flatbuffers.ByteBuffer, obj?:DeleteUserRequest):DeleteUserRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DeleteUserRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startDeleteUserRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endDeleteUserRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDeleteUserRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  DeleteUserRequest.startDeleteUserRequest(builder);
  return DeleteUserRequest.endDeleteUserRequest(builder);
}
}
