// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DepreciatedCheckLeagueRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DepreciatedCheckLeagueRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDepreciatedCheckLeagueRequest(bb:flatbuffers.ByteBuffer, obj?:DepreciatedCheckLeagueRequest):DepreciatedCheckLeagueRequest {
  return (obj || new DepreciatedCheckLeagueRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDepreciatedCheckLeagueRequest(bb:flatbuffers.ByteBuffer, obj?:DepreciatedCheckLeagueRequest):DepreciatedCheckLeagueRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DepreciatedCheckLeagueRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startDepreciatedCheckLeagueRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endDepreciatedCheckLeagueRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDepreciatedCheckLeagueRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  DepreciatedCheckLeagueRequest.startDepreciatedCheckLeagueRequest(builder);
  return DepreciatedCheckLeagueRequest.endDepreciatedCheckLeagueRequest(builder);
}
}
