// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ChatProfile } from '../../../../../royal/infrastructure/services/backend/protocol/chat-profile.js';
import { UserInfo } from '../../../../../royal/infrastructure/services/backend/protocol/user-info.js';


export class DragonNestTeamInviteResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DragonNestTeamInviteResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDragonNestTeamInviteResponse(bb:flatbuffers.ByteBuffer, obj?:DragonNestTeamInviteResponse):DragonNestTeamInviteResponse {
  return (obj || new DragonNestTeamInviteResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDragonNestTeamInviteResponse(bb:flatbuffers.ByteBuffer, obj?:DragonNestTeamInviteResponse):DragonNestTeamInviteResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DragonNestTeamInviteResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

userInfo(obj?:UserInfo):UserInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new UserInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

chatProfile(obj?:ChatProfile):ChatProfile|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ChatProfile()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

inviteDate():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startDragonNestTeamInviteResponse(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addUserInfo(builder:flatbuffers.Builder, userInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, userInfoOffset, 0);
}

static addChatProfile(builder:flatbuffers.Builder, chatProfileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, chatProfileOffset, 0);
}

static addInviteDate(builder:flatbuffers.Builder, inviteDate:bigint) {
  builder.addFieldInt64(2, inviteDate, BigInt('0'));
}

static endDragonNestTeamInviteResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
