// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum EnterDailyLightningRushFailReason {
  None = 0,
  AlreadyEntered = 1,
  EventNotActive = 2,
  IsAboutToEnd = 3
}
