// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class EnterSpaceMissionRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EnterSpaceMissionRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEnterSpaceMissionRequest(bb:flatbuffers.ByteBuffer, obj?:EnterSpaceMissionRequest):EnterSpaceMissionRequest {
  return (obj || new EnterSpaceMissionRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEnterSpaceMissionRequest(bb:flatbuffers.ByteBuffer, obj?:EnterSpaceMissionRequest):EnterSpaceMissionRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EnterSpaceMissionRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

level():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

step():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

spaceMissionConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startEnterSpaceMissionRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addLevel(builder:flatbuffers.Builder, level:number) {
  builder.addFieldInt32(0, level, 0);
}

static addStep(builder:flatbuffers.Builder, step:number) {
  builder.addFieldInt32(1, step, 0);
}

static addSpaceMissionConfigVersion(builder:flatbuffers.Builder, spaceMissionConfigVersion:number) {
  builder.addFieldInt32(2, spaceMissionConfigVersion, 0);
}

static endEnterSpaceMissionRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEnterSpaceMissionRequest(builder:flatbuffers.Builder, level:number, step:number, spaceMissionConfigVersion:number):flatbuffers.Offset {
  EnterSpaceMissionRequest.startEnterSpaceMissionRequest(builder);
  EnterSpaceMissionRequest.addLevel(builder, level);
  EnterSpaceMissionRequest.addStep(builder, step);
  EnterSpaceMissionRequest.addSpaceMissionConfigVersion(builder, spaceMissionConfigVersion);
  return EnterSpaceMissionRequest.endEnterSpaceMissionRequest(builder);
}
}
