// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum GameEventType {
  KINGS_CUP = 0,
  TEAM_BATTLE = 1,
  MADNESS_EVENT = 2,
  SKY_RACE = 3,
  PINATA_PARTY = 4,
  TEAM_TREASURE = 5,
  LIGHTNING_RUSH = 6,
  SPACE_MISSION = 7,
  BALLOON_RISE = 8,
  WEEKLY_LEADERBOARD = 9,
  WORLD_CUP = 10,
  LAVA_QUEST = 11,
  HIDDEN_TEMPLE = 12,
  MAGIC_CAULDRON = 13,
  DRAGON_NEST = 14,
  ARCHERY_ARENA = 15,
  DUKES_FORTUNE = 16,
  TEAM_TOURNAMENT = 17,
  TRAIN_JOURNEY = 18,
  OCEAN_ODYSSEY = 19,
  DAILY_LIGHTNING_RUSH = 20,
  PUZZLE_BREAK = 21
}
