// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetLightningRushInfoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetLightningRushInfoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetLightningRushInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetLightningRushInfoRequest):GetLightningRushInfoRequest {
  return (obj || new GetLightningRushInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetLightningRushInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetLightningRushInfoRequest):GetLightningRushInfoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetLightningRushInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

groupId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startGetLightningRushInfoRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addGroupId(builder:flatbuffers.Builder, groupId:bigint) {
  builder.addFieldInt64(0, groupId, BigInt('0'));
}

static endGetLightningRushInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetLightningRushInfoRequest(builder:flatbuffers.Builder, groupId:bigint):flatbuffers.Offset {
  GetLightningRushInfoRequest.startGetLightningRushInfoRequest(builder);
  GetLightningRushInfoRequest.addGroupId(builder, groupId);
  return GetLightningRushInfoRequest.endGetLightningRushInfoRequest(builder);
}
}
