// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MissionControlInfo } from '../../../../../royal/infrastructure/services/backend/protocol/mission-control-info.js';


export class GetMissionControlInfoResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetMissionControlInfoResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetMissionControlInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetMissionControlInfoResponse):GetMissionControlInfoResponse {
  return (obj || new GetMissionControlInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetMissionControlInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetMissionControlInfoResponse):GetMissionControlInfoResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetMissionControlInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

missionControlInfo(obj?:MissionControlInfo):MissionControlInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MissionControlInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startGetMissionControlInfoResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMissionControlInfo(builder:flatbuffers.Builder, missionControlInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, missionControlInfoOffset, 0);
}

static endGetMissionControlInfoResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetMissionControlInfoResponse(builder:flatbuffers.Builder, missionControlInfoOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetMissionControlInfoResponse.startGetMissionControlInfoResponse(builder);
  GetMissionControlInfoResponse.addMissionControlInfo(builder, missionControlInfoOffset);
  return GetMissionControlInfoResponse.endGetMissionControlInfoResponse(builder);
}
}
