// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetGoldenOffersInfoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetGoldenOffersInfoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetGoldenOffersInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetGoldenOffersInfoRequest):GetGoldenOffersInfoRequest {
  return (obj || new GetGoldenOffersInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetGoldenOffersInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetGoldenOffersInfoRequest):GetGoldenOffersInfoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetGoldenOffersInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startGetGoldenOffersInfoRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endGetGoldenOffersInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetGoldenOffersInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  GetGoldenOffersInfoRequest.startGetGoldenOffersInfoRequest(builder);
  return GetGoldenOffersInfoRequest.endGetGoldenOffersInfoRequest(builder);
}
}
