// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetDragonNestInfoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetDragonNestInfoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetDragonNestInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetDragonNestInfoRequest):GetDragonNestInfoRequest {
  return (obj || new GetDragonNestInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetDragonNestInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetDragonNestInfoRequest):GetDragonNestInfoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetDragonNestInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

eventId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

configVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startGetDragonNestInfoRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addEventId(builder:flatbuffers.Builder, eventId:number) {
  builder.addFieldInt32(0, eventId, 0);
}

static addConfigVersion(builder:flatbuffers.Builder, configVersion:number) {
  builder.addFieldInt32(1, configVersion, 0);
}

static endGetDragonNestInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetDragonNestInfoRequest(builder:flatbuffers.Builder, eventId:number, configVersion:number):flatbuffers.Offset {
  GetDragonNestInfoRequest.startGetDragonNestInfoRequest(builder);
  GetDragonNestInfoRequest.addEventId(builder, eventId);
  GetDragonNestInfoRequest.addConfigVersion(builder, configVersion);
  return GetDragonNestInfoRequest.endGetDragonNestInfoRequest(builder);
}
}
