// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetPendingFriendsRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetPendingFriendsRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetPendingFriendsRequest(bb:flatbuffers.ByteBuffer, obj?:GetPendingFriendsRequest):GetPendingFriendsRequest {
  return (obj || new GetPendingFriendsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetPendingFriendsRequest(bb:flatbuffers.ByteBuffer, obj?:GetPendingFriendsRequest):GetPendingFriendsRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetPendingFriendsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startGetPendingFriendsRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endGetPendingFriendsRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetPendingFriendsRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  GetPendingFriendsRequest.startGetPendingFriendsRequest(builder);
  return GetPendingFriendsRequest.endGetPendingFriendsRequest(builder);
}
}
