// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { LeaderboardInfoType } from '../../../../../royal/infrastructure/services/backend/protocol/leaderboard-info-type.js';
import { ResponseStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/response-status-code.js';
import { TeamTournamentFailReason } from '../../../../../royal/infrastructure/services/backend/protocol/team-tournament-fail-reason.js';
import { TeamTournamentGroupInfo } from '../../../../../royal/infrastructure/services/backend/protocol/team-tournament-group-info.js';
import { TeamTournamentInfo } from '../../../../../royal/infrastructure/services/backend/protocol/team-tournament-info.js';


export class GetTeamTournamentInfoResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetTeamTournamentInfoResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetTeamTournamentInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetTeamTournamentInfoResponse):GetTeamTournamentInfoResponse {
  return (obj || new GetTeamTournamentInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetTeamTournamentInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetTeamTournamentInfoResponse):GetTeamTournamentInfoResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetTeamTournamentInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():ResponseStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponseStatusCode.Success;
}

failReason():TeamTournamentFailReason {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : TeamTournamentFailReason.None;
}

teamTournamentInfo(obj?:TeamTournamentInfo):TeamTournamentInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new TeamTournamentInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

teamTournamentGroupInfo(obj?:TeamTournamentGroupInfo):TeamTournamentGroupInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new TeamTournamentGroupInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

usersHash():string|null
usersHash(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
usersHash(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

leaderboardInfoType():LeaderboardInfoType {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : LeaderboardInfoType.None;
}

static startGetTeamTournamentInfoResponse(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addStatus(builder:flatbuffers.Builder, status:ResponseStatusCode) {
  builder.addFieldInt8(0, status, ResponseStatusCode.Success);
}

static addFailReason(builder:flatbuffers.Builder, failReason:TeamTournamentFailReason) {
  builder.addFieldInt8(1, failReason, TeamTournamentFailReason.None);
}

static addTeamTournamentInfo(builder:flatbuffers.Builder, teamTournamentInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, teamTournamentInfoOffset, 0);
}

static addTeamTournamentGroupInfo(builder:flatbuffers.Builder, teamTournamentGroupInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, teamTournamentGroupInfoOffset, 0);
}

static addUsersHash(builder:flatbuffers.Builder, usersHashOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, usersHashOffset, 0);
}

static addLeaderboardInfoType(builder:flatbuffers.Builder, leaderboardInfoType:LeaderboardInfoType) {
  builder.addFieldInt8(5, leaderboardInfoType, LeaderboardInfoType.None);
}

static endGetTeamTournamentInfoResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
