// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetDragonNestSuggestionsAndInvitationsRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetDragonNestSuggestionsAndInvitationsRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetDragonNestSuggestionsAndInvitationsRequest(bb:flatbuffers.ByteBuffer, obj?:GetDragonNestSuggestionsAndInvitationsRequest):GetDragonNestSuggestionsAndInvitationsRequest {
  return (obj || new GetDragonNestSuggestionsAndInvitationsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetDragonNestSuggestionsAndInvitationsRequest(bb:flatbuffers.ByteBuffer, obj?:GetDragonNestSuggestionsAndInvitationsRequest):GetDragonNestSuggestionsAndInvitationsRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetDragonNestSuggestionsAndInvitationsRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

isTutorial():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startGetDragonNestSuggestionsAndInvitationsRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addIsTutorial(builder:flatbuffers.Builder, isTutorial:boolean) {
  builder.addFieldInt8(0, +isTutorial, +false);
}

static endGetDragonNestSuggestionsAndInvitationsRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetDragonNestSuggestionsAndInvitationsRequest(builder:flatbuffers.Builder, isTutorial:boolean):flatbuffers.Offset {
  GetDragonNestSuggestionsAndInvitationsRequest.startGetDragonNestSuggestionsAndInvitationsRequest(builder);
  GetDragonNestSuggestionsAndInvitationsRequest.addIsTutorial(builder, isTutorial);
  return GetDragonNestSuggestionsAndInvitationsRequest.endGetDragonNestSuggestionsAndInvitationsRequest(builder);
}
}
