// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetBalloonRiseInfoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetBalloonRiseInfoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetBalloonRiseInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetBalloonRiseInfoRequest):GetBalloonRiseInfoRequest {
  return (obj || new GetBalloonRiseInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetBalloonRiseInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetBalloonRiseInfoRequest):GetBalloonRiseInfoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetBalloonRiseInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

eventId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startGetBalloonRiseInfoRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addEventId(builder:flatbuffers.Builder, eventId:number) {
  builder.addFieldInt32(0, eventId, 0);
}

static endGetBalloonRiseInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetBalloonRiseInfoRequest(builder:flatbuffers.Builder, eventId:number):flatbuffers.Offset {
  GetBalloonRiseInfoRequest.startGetBalloonRiseInfoRequest(builder);
  GetBalloonRiseInfoRequest.addEventId(builder, eventId);
  return GetBalloonRiseInfoRequest.endGetBalloonRiseInfoRequest(builder);
}
}
