// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetUpcomingEventInfoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetUpcomingEventInfoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetUpcomingEventInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetUpcomingEventInfoRequest):GetUpcomingEventInfoRequest {
  return (obj || new GetUpcomingEventInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetUpcomingEventInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetUpcomingEventInfoRequest):GetUpcomingEventInfoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetUpcomingEventInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startGetUpcomingEventInfoRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endGetUpcomingEventInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetUpcomingEventInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  GetUpcomingEventInfoRequest.startGetUpcomingEventInfoRequest(builder);
  return GetUpcomingEventInfoRequest.endGetUpcomingEventInfoRequest(builder);
}
}
