// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetOceanOdysseyInfoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetOceanOdysseyInfoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetOceanOdysseyInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetOceanOdysseyInfoRequest):GetOceanOdysseyInfoRequest {
  return (obj || new GetOceanOdysseyInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetOceanOdysseyInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetOceanOdysseyInfoRequest):GetOceanOdysseyInfoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetOceanOdysseyInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

eventId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startGetOceanOdysseyInfoRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addEventId(builder:flatbuffers.Builder, eventId:number) {
  builder.addFieldInt32(0, eventId, 0);
}

static endGetOceanOdysseyInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetOceanOdysseyInfoRequest(builder:flatbuffers.Builder, eventId:number):flatbuffers.Offset {
  GetOceanOdysseyInfoRequest.startGetOceanOdysseyInfoRequest(builder);
  GetOceanOdysseyInfoRequest.addEventId(builder, eventId);
  return GetOceanOdysseyInfoRequest.endGetOceanOdysseyInfoRequest(builder);
}
}
