// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetKingsCupInfoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetKingsCupInfoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetKingsCupInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetKingsCupInfoRequest):GetKingsCupInfoRequest {
  return (obj || new GetKingsCupInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetKingsCupInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetKingsCupInfoRequest):GetKingsCupInfoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetKingsCupInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

groupId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startGetKingsCupInfoRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addGroupId(builder:flatbuffers.Builder, groupId:bigint) {
  builder.addFieldInt64(0, groupId, BigInt('0'));
}

static endGetKingsCupInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetKingsCupInfoRequest(builder:flatbuffers.Builder, groupId:bigint):flatbuffers.Offset {
  GetKingsCupInfoRequest.startGetKingsCupInfoRequest(builder);
  GetKingsCupInfoRequest.addGroupId(builder, groupId);
  return GetKingsCupInfoRequest.endGetKingsCupInfoRequest(builder);
}
}
