// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetWeeklyLeaderboardInfoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetWeeklyLeaderboardInfoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetWeeklyLeaderboardInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetWeeklyLeaderboardInfoRequest):GetWeeklyLeaderboardInfoRequest {
  return (obj || new GetWeeklyLeaderboardInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetWeeklyLeaderboardInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetWeeklyLeaderboardInfoRequest):GetWeeklyLeaderboardInfoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetWeeklyLeaderboardInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

userEventId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

configVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startGetWeeklyLeaderboardInfoRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addUserEventId(builder:flatbuffers.Builder, userEventId:number) {
  builder.addFieldInt32(0, userEventId, 0);
}

static addConfigVersion(builder:flatbuffers.Builder, configVersion:number) {
  builder.addFieldInt32(1, configVersion, 0);
}

static endGetWeeklyLeaderboardInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetWeeklyLeaderboardInfoRequest(builder:flatbuffers.Builder, userEventId:number, configVersion:number):flatbuffers.Offset {
  GetWeeklyLeaderboardInfoRequest.startGetWeeklyLeaderboardInfoRequest(builder);
  GetWeeklyLeaderboardInfoRequest.addUserEventId(builder, userEventId);
  GetWeeklyLeaderboardInfoRequest.addConfigVersion(builder, configVersion);
  return GetWeeklyLeaderboardInfoRequest.endGetWeeklyLeaderboardInfoRequest(builder);
}
}
