// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetTeamBattleInfoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetTeamBattleInfoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetTeamBattleInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetTeamBattleInfoRequest):GetTeamBattleInfoRequest {
  return (obj || new GetTeamBattleInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetTeamBattleInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetTeamBattleInfoRequest):GetTeamBattleInfoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetTeamBattleInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

groupId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

teamId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startGetTeamBattleInfoRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addGroupId(builder:flatbuffers.Builder, groupId:bigint) {
  builder.addFieldInt64(0, groupId, BigInt('0'));
}

static addTeamId(builder:flatbuffers.Builder, teamId:bigint) {
  builder.addFieldInt64(1, teamId, BigInt('0'));
}

static endGetTeamBattleInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetTeamBattleInfoRequest(builder:flatbuffers.Builder, groupId:bigint, teamId:bigint):flatbuffers.Offset {
  GetTeamBattleInfoRequest.startGetTeamBattleInfoRequest(builder);
  GetTeamBattleInfoRequest.addGroupId(builder, groupId);
  GetTeamBattleInfoRequest.addTeamId(builder, teamId);
  return GetTeamBattleInfoRequest.endGetTeamBattleInfoRequest(builder);
}
}
