// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetSpaceMissionInfoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetSpaceMissionInfoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetSpaceMissionInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetSpaceMissionInfoRequest):GetSpaceMissionInfoRequest {
  return (obj || new GetSpaceMissionInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetSpaceMissionInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetSpaceMissionInfoRequest):GetSpaceMissionInfoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetSpaceMissionInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

groupId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

spaceMissionConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startGetSpaceMissionInfoRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addGroupId(builder:flatbuffers.Builder, groupId:bigint) {
  builder.addFieldInt64(0, groupId, BigInt('0'));
}

static addSpaceMissionConfigVersion(builder:flatbuffers.Builder, spaceMissionConfigVersion:number) {
  builder.addFieldInt32(1, spaceMissionConfigVersion, 0);
}

static endGetSpaceMissionInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetSpaceMissionInfoRequest(builder:flatbuffers.Builder, groupId:bigint, spaceMissionConfigVersion:number):flatbuffers.Offset {
  GetSpaceMissionInfoRequest.startGetSpaceMissionInfoRequest(builder);
  GetSpaceMissionInfoRequest.addGroupId(builder, groupId);
  GetSpaceMissionInfoRequest.addSpaceMissionConfigVersion(builder, spaceMissionConfigVersion);
  return GetSpaceMissionInfoRequest.endGetSpaceMissionInfoRequest(builder);
}
}
