// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetMissionPursuitInfoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetMissionPursuitInfoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetMissionPursuitInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetMissionPursuitInfoRequest):GetMissionPursuitInfoRequest {
  return (obj || new GetMissionPursuitInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetMissionPursuitInfoRequest(bb:flatbuffers.ByteBuffer, obj?:GetMissionPursuitInfoRequest):GetMissionPursuitInfoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetMissionPursuitInfoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

eventId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startGetMissionPursuitInfoRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addEventId(builder:flatbuffers.Builder, eventId:number) {
  builder.addFieldInt32(0, eventId, 0);
}

static endGetMissionPursuitInfoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetMissionPursuitInfoRequest(builder:flatbuffers.Builder, eventId:number):flatbuffers.Offset {
  GetMissionPursuitInfoRequest.startGetMissionPursuitInfoRequest(builder);
  GetMissionPursuitInfoRequest.addEventId(builder, eventId);
  return GetMissionPursuitInfoRequest.endGetMissionPursuitInfoRequest(builder);
}
}
