// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PuzzleBreakUserConfigInfo } from '../../../../../royal/infrastructure/services/backend/protocol/puzzle-break-user-config-info.js';


export class GetPuzzleBreakInfoResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetPuzzleBreakInfoResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetPuzzleBreakInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetPuzzleBreakInfoResponse):GetPuzzleBreakInfoResponse {
  return (obj || new GetPuzzleBreakInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetPuzzleBreakInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetPuzzleBreakInfoResponse):GetPuzzleBreakInfoResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetPuzzleBreakInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

puzzleBreakUserInfo(obj?:PuzzleBreakUserConfigInfo):PuzzleBreakUserConfigInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PuzzleBreakUserConfigInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startGetPuzzleBreakInfoResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPuzzleBreakUserInfo(builder:flatbuffers.Builder, puzzleBreakUserInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, puzzleBreakUserInfoOffset, 0);
}

static endGetPuzzleBreakInfoResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetPuzzleBreakInfoResponse(builder:flatbuffers.Builder, puzzleBreakUserInfoOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetPuzzleBreakInfoResponse.startGetPuzzleBreakInfoResponse(builder);
  GetPuzzleBreakInfoResponse.addPuzzleBreakUserInfo(builder, puzzleBreakUserInfoOffset);
  return GetPuzzleBreakInfoResponse.endGetPuzzleBreakInfoResponse(builder);
}
}
