// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DynamicOfferInfo } from '../../../../../royal/infrastructure/services/backend/protocol/dynamic-offer-info.js';
import { DynamicOfferInfoOld } from '../../../../../royal/infrastructure/services/backend/protocol/dynamic-offer-info-old.js';
import { LavaQuestInfo } from '../../../../../royal/infrastructure/services/backend/protocol/lava-quest-info.js';
import { ResponseStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/response-status-code.js';
import { UserDynamicSegmentInfo } from '../../../../../royal/infrastructure/services/backend/protocol/user-dynamic-segment-info.js';
import { WorldCupInfo } from '../../../../../royal/infrastructure/services/backend/protocol/world-cup-info.js';


export class GetEventInfoResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetEventInfoResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetEventInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetEventInfoResponse):GetEventInfoResponse {
  return (obj || new GetEventInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetEventInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetEventInfoResponse):GetEventInfoResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetEventInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():ResponseStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponseStatusCode.Success;
}

worldCupServerEventInfo(obj?:WorldCupInfo):WorldCupInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new WorldCupInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

dynamicOfferEventInfo(obj?:DynamicOfferInfoOld):DynamicOfferInfoOld|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new DynamicOfferInfoOld()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

lavaQuestInfo(obj?:LavaQuestInfo):LavaQuestInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new LavaQuestInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

dynamicOfferEventInfoList(index: number, obj?:DynamicOfferInfo):DynamicOfferInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new DynamicOfferInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

dynamicOfferEventInfoListLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

dynamicOfferDisableFlags(index: number):string
dynamicOfferDisableFlags(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
dynamicOfferDisableFlags(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

dynamicOfferDisableFlagsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

userDynamicSegmentInfo(obj?:UserDynamicSegmentInfo):UserDynamicSegmentInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new UserDynamicSegmentInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startGetEventInfoResponse(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addStatus(builder:flatbuffers.Builder, status:ResponseStatusCode) {
  builder.addFieldInt8(0, status, ResponseStatusCode.Success);
}

static addWorldCupServerEventInfo(builder:flatbuffers.Builder, worldCupServerEventInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, worldCupServerEventInfoOffset, 0);
}

static addDynamicOfferEventInfo(builder:flatbuffers.Builder, dynamicOfferEventInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, dynamicOfferEventInfoOffset, 0);
}

static addLavaQuestInfo(builder:flatbuffers.Builder, lavaQuestInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, lavaQuestInfoOffset, 0);
}

static addDynamicOfferEventInfoList(builder:flatbuffers.Builder, dynamicOfferEventInfoListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, dynamicOfferEventInfoListOffset, 0);
}

static createDynamicOfferEventInfoListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDynamicOfferEventInfoListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addDynamicOfferDisableFlags(builder:flatbuffers.Builder, dynamicOfferDisableFlagsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, dynamicOfferDisableFlagsOffset, 0);
}

static createDynamicOfferDisableFlagsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDynamicOfferDisableFlagsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addUserDynamicSegmentInfo(builder:flatbuffers.Builder, userDynamicSegmentInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, userDynamicSegmentInfoOffset, 0);
}

static endGetEventInfoResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
