// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ArcheryArenaFailReason } from '../../../../../royal/infrastructure/services/backend/protocol/archery-arena-fail-reason.js';
import { ArcheryArenaGroupInfo } from '../../../../../royal/infrastructure/services/backend/protocol/archery-arena-group-info.js';
import { ArcheryArenaInfo } from '../../../../../royal/infrastructure/services/backend/protocol/archery-arena-info.js';
import { ResponseStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/response-status-code.js';


export class GetArcheryArenaInfoResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetArcheryArenaInfoResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetArcheryArenaInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetArcheryArenaInfoResponse):GetArcheryArenaInfoResponse {
  return (obj || new GetArcheryArenaInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetArcheryArenaInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetArcheryArenaInfoResponse):GetArcheryArenaInfoResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetArcheryArenaInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():ResponseStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponseStatusCode.Success;
}

failReason():ArcheryArenaFailReason {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ArcheryArenaFailReason.None;
}

archeryArenaGroupInfo(obj?:ArcheryArenaGroupInfo):ArcheryArenaGroupInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new ArcheryArenaGroupInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

archeryArenaInfo(obj?:ArcheryArenaInfo):ArcheryArenaInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ArcheryArenaInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startGetArcheryArenaInfoResponse(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addStatus(builder:flatbuffers.Builder, status:ResponseStatusCode) {
  builder.addFieldInt8(0, status, ResponseStatusCode.Success);
}

static addFailReason(builder:flatbuffers.Builder, failReason:ArcheryArenaFailReason) {
  builder.addFieldInt8(1, failReason, ArcheryArenaFailReason.None);
}

static addArcheryArenaGroupInfo(builder:flatbuffers.Builder, archeryArenaGroupInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, archeryArenaGroupInfoOffset, 0);
}

static addArcheryArenaInfo(builder:flatbuffers.Builder, archeryArenaInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, archeryArenaInfoOffset, 0);
}

static endGetArcheryArenaInfoResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
