// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetUpcomingEventInfoResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetUpcomingEventInfoResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetUpcomingEventInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetUpcomingEventInfoResponse):GetUpcomingEventInfoResponse {
  return (obj || new GetUpcomingEventInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetUpcomingEventInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetUpcomingEventInfoResponse):GetUpcomingEventInfoResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetUpcomingEventInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

upcomingTeamTournamentStartDate():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startGetUpcomingEventInfoResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addUpcomingTeamTournamentStartDate(builder:flatbuffers.Builder, upcomingTeamTournamentStartDate:bigint) {
  builder.addFieldInt64(0, upcomingTeamTournamentStartDate, BigInt('0'));
}

static endGetUpcomingEventInfoResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetUpcomingEventInfoResponse(builder:flatbuffers.Builder, upcomingTeamTournamentStartDate:bigint):flatbuffers.Offset {
  GetUpcomingEventInfoResponse.startGetUpcomingEventInfoResponse(builder);
  GetUpcomingEventInfoResponse.addUpcomingTeamTournamentStartDate(builder, upcomingTeamTournamentStartDate);
  return GetUpcomingEventInfoResponse.endGetUpcomingEventInfoResponse(builder);
}
}
