// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { GoldenOffersInfo } from '../../../../../royal/infrastructure/services/backend/protocol/golden-offers-info.js';


export class GetGoldenOffersInfoResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetGoldenOffersInfoResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetGoldenOffersInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetGoldenOffersInfoResponse):GetGoldenOffersInfoResponse {
  return (obj || new GetGoldenOffersInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetGoldenOffersInfoResponse(bb:flatbuffers.ByteBuffer, obj?:GetGoldenOffersInfoResponse):GetGoldenOffersInfoResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetGoldenOffersInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

goldenOffersInfo(obj?:GoldenOffersInfo):GoldenOffersInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new GoldenOffersInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startGetGoldenOffersInfoResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addGoldenOffersInfo(builder:flatbuffers.Builder, goldenOffersInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, goldenOffersInfoOffset, 0);
}

static endGetGoldenOffersInfoResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetGoldenOffersInfoResponse(builder:flatbuffers.Builder, goldenOffersInfoOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetGoldenOffersInfoResponse.startGetGoldenOffersInfoResponse(builder);
  GetGoldenOffersInfoResponse.addGoldenOffersInfo(builder, goldenOffersInfoOffset);
  return GetGoldenOffersInfoResponse.endGetGoldenOffersInfoResponse(builder);
}
}
