// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ChatProfile } from '../../../../../royal/infrastructure/services/backend/protocol/chat-profile.js';
import { SpecialChatProfile } from '../../../../../royal/infrastructure/services/backend/protocol/special-chat-profile.js';


export class HelpLifeRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):HelpLifeRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHelpLifeRequest(bb:flatbuffers.ByteBuffer, obj?:HelpLifeRequest):HelpLifeRequest {
  return (obj || new HelpLifeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHelpLifeRequest(bb:flatbuffers.ByteBuffer, obj?:HelpLifeRequest):HelpLifeRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HelpLifeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

toUserId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

ownerChatProfile(obj?:ChatProfile):ChatProfile|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ChatProfile()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

ownerSpecialChatProfile(obj?:SpecialChatProfile):SpecialChatProfile|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new SpecialChatProfile()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startHelpLifeRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addToUserId(builder:flatbuffers.Builder, toUserId:bigint) {
  builder.addFieldInt64(0, toUserId, BigInt('0'));
}

static addOwnerChatProfile(builder:flatbuffers.Builder, ownerChatProfileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, ownerChatProfileOffset, 0);
}

static addOwnerSpecialChatProfile(builder:flatbuffers.Builder, ownerSpecialChatProfileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, ownerSpecialChatProfileOffset, 0);
}

static endHelpLifeRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
