// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { KingsCupUser } from '../../../../../royal/infrastructure/services/backend/protocol/kings-cup-user.js';
import { UserEventStatus } from '../../../../../royal/infrastructure/services/backend/protocol/user-event-status.js';


export class KingsCupInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):KingsCupInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsKingsCupInfo(bb:flatbuffers.ByteBuffer, obj?:KingsCupInfo):KingsCupInfo {
  return (obj || new KingsCupInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsKingsCupInfo(bb:flatbuffers.ByteBuffer, obj?:KingsCupInfo):KingsCupInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new KingsCupInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

groupId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

status():UserEventStatus {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : UserEventStatus.Continue;
}

rank():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

remainingTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

isEnteredEvent():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

users(index: number, obj?:KingsCupUser):KingsCupUser|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new KingsCupUser()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

usersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

serverEventId():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startKingsCupInfo(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addGroupId(builder:flatbuffers.Builder, groupId:bigint) {
  builder.addFieldInt64(0, groupId, BigInt('0'));
}

static addStatus(builder:flatbuffers.Builder, status:UserEventStatus) {
  builder.addFieldInt8(1, status, UserEventStatus.Continue);
}

static addRank(builder:flatbuffers.Builder, rank:number) {
  builder.addFieldInt32(2, rank, 0);
}

static addRemainingTime(builder:flatbuffers.Builder, remainingTime:bigint) {
  builder.addFieldInt64(3, remainingTime, BigInt('0'));
}

static addIsEnteredEvent(builder:flatbuffers.Builder, isEnteredEvent:bigint) {
  builder.addFieldInt64(4, isEnteredEvent, BigInt('0'));
}

static addUsers(builder:flatbuffers.Builder, usersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, usersOffset, 0);
}

static createUsersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startUsersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addServerEventId(builder:flatbuffers.Builder, serverEventId:number) {
  builder.addFieldInt32(6, serverEventId, 0);
}

static endKingsCupInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createKingsCupInfo(builder:flatbuffers.Builder, groupId:bigint, status:UserEventStatus, rank:number, remainingTime:bigint, isEnteredEvent:bigint, usersOffset:flatbuffers.Offset, serverEventId:number):flatbuffers.Offset {
  KingsCupInfo.startKingsCupInfo(builder);
  KingsCupInfo.addGroupId(builder, groupId);
  KingsCupInfo.addStatus(builder, status);
  KingsCupInfo.addRank(builder, rank);
  KingsCupInfo.addRemainingTime(builder, remainingTime);
  KingsCupInfo.addIsEnteredEvent(builder, isEnteredEvent);
  KingsCupInfo.addUsers(builder, usersOffset);
  KingsCupInfo.addServerEventId(builder, serverEventId);
  return KingsCupInfo.endKingsCupInfo(builder);
}
}
