// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum LeaderboardInfoType {
  None = 0,
  ScoresOnly = 1,
  WithBasicUserData = 2
}
