// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class LevelWinMultiplier {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LevelWinMultiplier {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLevelWinMultiplier(bb:flatbuffers.ByteBuffer, obj?:LevelWinMultiplier):LevelWinMultiplier {
  return (obj || new LevelWinMultiplier()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLevelWinMultiplier(bb:flatbuffers.ByteBuffer, obj?:LevelWinMultiplier):LevelWinMultiplier {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LevelWinMultiplier()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

level():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

multiplier():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startLevelWinMultiplier(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addLevel(builder:flatbuffers.Builder, level:number) {
  builder.addFieldInt32(0, level, 0);
}

static addMultiplier(builder:flatbuffers.Builder, multiplier:number) {
  builder.addFieldInt32(1, multiplier, 0);
}

static endLevelWinMultiplier(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLevelWinMultiplier(builder:flatbuffers.Builder, level:number, multiplier:number):flatbuffers.Offset {
  LevelWinMultiplier.startLevelWinMultiplier(builder);
  LevelWinMultiplier.addLevel(builder, level);
  LevelWinMultiplier.addMultiplier(builder, multiplier);
  return LevelWinMultiplier.endLevelWinMultiplier(builder);
}
}
