// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { SeasonalCardCollectionGift } from '../../../../../royal/infrastructure/services/backend/protocol/seasonal-card-collection-gift.js';


export enum MessageType {
  NONE = 0,
  SeasonalCardCollectionGift = 1
}

export function unionToMessageType(
  type: MessageType,
  accessor: (obj:SeasonalCardCollectionGift) => SeasonalCardCollectionGift|null
): SeasonalCardCollectionGift|null {
  switch(MessageType[type]) {
    case 'NONE': return null; 
    case 'SeasonalCardCollectionGift': return accessor(new SeasonalCardCollectionGift())! as SeasonalCardCollectionGift;
    default: return null;
  }
}

export function unionListToMessageType(
  type: MessageType, 
  accessor: (index: number, obj:SeasonalCardCollectionGift) => SeasonalCardCollectionGift|null, 
  index: number
): SeasonalCardCollectionGift|null {
  switch(MessageType[type]) {
    case 'NONE': return null; 
    case 'SeasonalCardCollectionGift': return accessor(index, new SeasonalCardCollectionGift())! as SeasonalCardCollectionGift;
    default: return null;
  }
}
