// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { WorldCupUser } from '../../../../../royal/infrastructure/services/backend/protocol/world-cup-user.js';


export class NationalStageInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NationalStageInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNationalStageInfo(bb:flatbuffers.ByteBuffer, obj?:NationalStageInfo):NationalStageInfo {
  return (obj || new NationalStageInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNationalStageInfo(bb:flatbuffers.ByteBuffer, obj?:NationalStageInfo):NationalStageInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NationalStageInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

topUsersLength(index: number, obj?:WorldCupUser):WorldCupUser|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new WorldCupUser()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

topUsersLengthLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

bottomUsersLength(index: number, obj?:WorldCupUser):WorldCupUser|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new WorldCupUser()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

bottomUsersLengthLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startNationalStageInfo(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTopUsersLength(builder:flatbuffers.Builder, topUsersLengthOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, topUsersLengthOffset, 0);
}

static createTopUsersLengthVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTopUsersLengthVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addBottomUsersLength(builder:flatbuffers.Builder, bottomUsersLengthOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, bottomUsersLengthOffset, 0);
}

static createBottomUsersLengthVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startBottomUsersLengthVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endNationalStageInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNationalStageInfo(builder:flatbuffers.Builder, topUsersLengthOffset:flatbuffers.Offset, bottomUsersLengthOffset:flatbuffers.Offset):flatbuffers.Offset {
  NationalStageInfo.startNationalStageInfo(builder);
  NationalStageInfo.addTopUsersLength(builder, topUsersLengthOffset);
  NationalStageInfo.addBottomUsersLength(builder, bottomUsersLengthOffset);
  return NationalStageInfo.endNationalStageInfo(builder);
}
}
