// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TeamChatData } from '../../../../../royal/infrastructure/services/backend/protocol/team-chat-data.js';


export class PendingJoinTeamResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PendingJoinTeamResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPendingJoinTeamResponse(bb:flatbuffers.ByteBuffer, obj?:PendingJoinTeamResponse):PendingJoinTeamResponse {
  return (obj || new PendingJoinTeamResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPendingJoinTeamResponse(bb:flatbuffers.ByteBuffer, obj?:PendingJoinTeamResponse):PendingJoinTeamResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PendingJoinTeamResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

isAccepted():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

teamId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

teamChatData(obj?:TeamChatData):TeamChatData|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new TeamChatData()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startPendingJoinTeamResponse(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addIsAccepted(builder:flatbuffers.Builder, isAccepted:boolean) {
  builder.addFieldInt8(0, +isAccepted, +false);
}

static addTeamId(builder:flatbuffers.Builder, teamId:bigint) {
  builder.addFieldInt64(1, teamId, BigInt('0'));
}

static addTeamChatData(builder:flatbuffers.Builder, teamChatDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, teamChatDataOffset, 0);
}

static endPendingJoinTeamResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
