// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PurchaseTransactionInfo } from '../../../../../royal/infrastructure/services/backend/protocol/purchase-transaction-info.js';
import { PurchaseVerificationStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/purchase-verification-status-code.js';
import { ResponseStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/response-status-code.js';
import { UserProgress } from '../../../../../royal/infrastructure/services/backend/protocol/user-progress.js';


export class PurchaseVerificationResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PurchaseVerificationResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPurchaseVerificationResponse(bb:flatbuffers.ByteBuffer, obj?:PurchaseVerificationResponse):PurchaseVerificationResponse {
  return (obj || new PurchaseVerificationResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPurchaseVerificationResponse(bb:flatbuffers.ByteBuffer, obj?:PurchaseVerificationResponse):PurchaseVerificationResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PurchaseVerificationResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():ResponseStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponseStatusCode.Success;
}

verificationStatus():PurchaseVerificationStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : PurchaseVerificationStatusCode.Verified;
}

deprecatedUserProgress(obj?:UserProgress):UserProgress|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new UserProgress()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

deprecatedProcessedTransactionIdsLength(index: number):string
deprecatedProcessedTransactionIdsLength(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
deprecatedProcessedTransactionIdsLength(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

deprecatedProcessedTransactionIdsLengthLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

purchaseTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

isSandbox():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

processedTransactionInfosLength(index: number, obj?:PurchaseTransactionInfo):PurchaseTransactionInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new PurchaseTransactionInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

processedTransactionInfosLengthLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPurchaseVerificationResponse(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addStatus(builder:flatbuffers.Builder, status:ResponseStatusCode) {
  builder.addFieldInt8(0, status, ResponseStatusCode.Success);
}

static addVerificationStatus(builder:flatbuffers.Builder, verificationStatus:PurchaseVerificationStatusCode) {
  builder.addFieldInt8(1, verificationStatus, PurchaseVerificationStatusCode.Verified);
}

static addDeprecatedUserProgress(builder:flatbuffers.Builder, deprecatedUserProgressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, deprecatedUserProgressOffset, 0);
}

static addDeprecatedProcessedTransactionIdsLength(builder:flatbuffers.Builder, deprecatedProcessedTransactionIdsLengthOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, deprecatedProcessedTransactionIdsLengthOffset, 0);
}

static createDeprecatedProcessedTransactionIdsLengthVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDeprecatedProcessedTransactionIdsLengthVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addPurchaseTime(builder:flatbuffers.Builder, purchaseTime:bigint) {
  builder.addFieldInt64(4, purchaseTime, BigInt('0'));
}

static addIsSandbox(builder:flatbuffers.Builder, isSandbox:boolean) {
  builder.addFieldInt8(5, +isSandbox, +false);
}

static addProcessedTransactionInfosLength(builder:flatbuffers.Builder, processedTransactionInfosLengthOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, processedTransactionInfosLengthOffset, 0);
}

static createProcessedTransactionInfosLengthVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startProcessedTransactionInfosLengthVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPurchaseVerificationResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
