// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PurchaseInMaintenanceModeRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PurchaseInMaintenanceModeRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPurchaseInMaintenanceModeRequest(bb:flatbuffers.ByteBuffer, obj?:PurchaseInMaintenanceModeRequest):PurchaseInMaintenanceModeRequest {
  return (obj || new PurchaseInMaintenanceModeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPurchaseInMaintenanceModeRequest(bb:flatbuffers.ByteBuffer, obj?:PurchaseInMaintenanceModeRequest):PurchaseInMaintenanceModeRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PurchaseInMaintenanceModeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

productIds(index: number):string
productIds(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
productIds(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

productIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPurchaseInMaintenanceModeRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addProductIds(builder:flatbuffers.Builder, productIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, productIdsOffset, 0);
}

static createProductIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startProductIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPurchaseInMaintenanceModeRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPurchaseInMaintenanceModeRequest(builder:flatbuffers.Builder, productIdsOffset:flatbuffers.Offset):flatbuffers.Offset {
  PurchaseInMaintenanceModeRequest.startPurchaseInMaintenanceModeRequest(builder);
  PurchaseInMaintenanceModeRequest.addProductIds(builder, productIdsOffset);
  return PurchaseInMaintenanceModeRequest.endPurchaseInMaintenanceModeRequest(builder);
}
}
