// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ResponseStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/response-status-code.js';


export class PurchaseInMaintenanceModeResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PurchaseInMaintenanceModeResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPurchaseInMaintenanceModeResponse(bb:flatbuffers.ByteBuffer, obj?:PurchaseInMaintenanceModeResponse):PurchaseInMaintenanceModeResponse {
  return (obj || new PurchaseInMaintenanceModeResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPurchaseInMaintenanceModeResponse(bb:flatbuffers.ByteBuffer, obj?:PurchaseInMaintenanceModeResponse):PurchaseInMaintenanceModeResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PurchaseInMaintenanceModeResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():ResponseStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponseStatusCode.Success;
}

static startPurchaseInMaintenanceModeResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addStatus(builder:flatbuffers.Builder, status:ResponseStatusCode) {
  builder.addFieldInt8(0, status, ResponseStatusCode.Success);
}

static endPurchaseInMaintenanceModeResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPurchaseInMaintenanceModeResponse(builder:flatbuffers.Builder, status:ResponseStatusCode):flatbuffers.Offset {
  PurchaseInMaintenanceModeResponse.startPurchaseInMaintenanceModeResponse(builder);
  PurchaseInMaintenanceModeResponse.addStatus(builder, status);
  return PurchaseInMaintenanceModeResponse.endPurchaseInMaintenanceModeResponse(builder);
}
}
