// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PurchaseTransactionInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PurchaseTransactionInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPurchaseTransactionInfo(bb:flatbuffers.ByteBuffer, obj?:PurchaseTransactionInfo):PurchaseTransactionInfo {
  return (obj || new PurchaseTransactionInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPurchaseTransactionInfo(bb:flatbuffers.ByteBuffer, obj?:PurchaseTransactionInfo):PurchaseTransactionInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PurchaseTransactionInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

productId():string|null
productId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
productId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

transactionId():string|null
transactionId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
transactionId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

purchaseToken():string|null
purchaseToken(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
purchaseToken(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

purchaseTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

isFailed():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startPurchaseTransactionInfo(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addProductId(builder:flatbuffers.Builder, productIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, productIdOffset, 0);
}

static addTransactionId(builder:flatbuffers.Builder, transactionIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, transactionIdOffset, 0);
}

static addPurchaseToken(builder:flatbuffers.Builder, purchaseTokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, purchaseTokenOffset, 0);
}

static addPurchaseTime(builder:flatbuffers.Builder, purchaseTime:bigint) {
  builder.addFieldInt64(3, purchaseTime, BigInt('0'));
}

static addIsFailed(builder:flatbuffers.Builder, isFailed:boolean) {
  builder.addFieldInt8(4, +isFailed, +false);
}

static endPurchaseTransactionInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPurchaseTransactionInfo(builder:flatbuffers.Builder, productIdOffset:flatbuffers.Offset, transactionIdOffset:flatbuffers.Offset, purchaseTokenOffset:flatbuffers.Offset, purchaseTime:bigint, isFailed:boolean):flatbuffers.Offset {
  PurchaseTransactionInfo.startPurchaseTransactionInfo(builder);
  PurchaseTransactionInfo.addProductId(builder, productIdOffset);
  PurchaseTransactionInfo.addTransactionId(builder, transactionIdOffset);
  PurchaseTransactionInfo.addPurchaseToken(builder, purchaseTokenOffset);
  PurchaseTransactionInfo.addPurchaseTime(builder, purchaseTime);
  PurchaseTransactionInfo.addIsFailed(builder, isFailed);
  return PurchaseTransactionInfo.endPurchaseTransactionInfo(builder);
}
}
