// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RequestPlatform {
  DefaultValueFromOldClients = 0,
  IOS = 1,
  Android = 2,
  Editor = 3,
  Huawei = 4,
  Samsung = 5,
  Amazon = 6
}
