// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CardInfo } from '../../../../../royal/infrastructure/services/backend/protocol/card-info.js';


export class SeasonalCardCollectionCardDonatedResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SeasonalCardCollectionCardDonatedResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSeasonalCardCollectionCardDonatedResponse(bb:flatbuffers.ByteBuffer, obj?:SeasonalCardCollectionCardDonatedResponse):SeasonalCardCollectionCardDonatedResponse {
  return (obj || new SeasonalCardCollectionCardDonatedResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSeasonalCardCollectionCardDonatedResponse(bb:flatbuffers.ByteBuffer, obj?:SeasonalCardCollectionCardDonatedResponse):SeasonalCardCollectionCardDonatedResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SeasonalCardCollectionCardDonatedResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

userId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

cardInfo(obj?:CardInfo):CardInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CardInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSeasonalCardCollectionCardDonatedResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addUserId(builder:flatbuffers.Builder, userId:bigint) {
  builder.addFieldInt64(0, userId, BigInt('0'));
}

static addCardInfo(builder:flatbuffers.Builder, cardInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, cardInfoOffset, 0);
}

static endSeasonalCardCollectionCardDonatedResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
