// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SegmentOfferInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SegmentOfferInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSegmentOfferInfo(bb:flatbuffers.ByteBuffer, obj?:SegmentOfferInfo):SegmentOfferInfo {
  return (obj || new SegmentOfferInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSegmentOfferInfo(bb:flatbuffers.ByteBuffer, obj?:SegmentOfferInfo):SegmentOfferInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SegmentOfferInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

configVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

config():string|null
config(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
config(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

step():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startSegmentOfferInfo(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addConfigVersion(builder:flatbuffers.Builder, configVersion:number) {
  builder.addFieldInt32(0, configVersion, 0);
}

static addConfig(builder:flatbuffers.Builder, configOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, configOffset, 0);
}

static addStep(builder:flatbuffers.Builder, step:number) {
  builder.addFieldInt32(2, step, 0);
}

static endSegmentOfferInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSegmentOfferInfo(builder:flatbuffers.Builder, configVersion:number, configOffset:flatbuffers.Offset, step:number):flatbuffers.Offset {
  SegmentOfferInfo.startSegmentOfferInfo(builder);
  SegmentOfferInfo.addConfigVersion(builder, configVersion);
  SegmentOfferInfo.addConfig(builder, configOffset);
  SegmentOfferInfo.addStep(builder, step);
  return SegmentOfferInfo.endSegmentOfferInfo(builder);
}
}
