// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CoopEventInvitationOperationStatus } from '../../../../../royal/infrastructure/services/backend/protocol/coop-event-invitation-operation-status.js';


export class SendTrainJourneyTeamInviteResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SendTrainJourneyTeamInviteResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSendTrainJourneyTeamInviteResponse(bb:flatbuffers.ByteBuffer, obj?:SendTrainJourneyTeamInviteResponse):SendTrainJourneyTeamInviteResponse {
  return (obj || new SendTrainJourneyTeamInviteResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSendTrainJourneyTeamInviteResponse(bb:flatbuffers.ByteBuffer, obj?:SendTrainJourneyTeamInviteResponse):SendTrainJourneyTeamInviteResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SendTrainJourneyTeamInviteResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

operationStatus():CoopEventInvitationOperationStatus {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : CoopEventInvitationOperationStatus.Ok;
}

static startSendTrainJourneyTeamInviteResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addOperationStatus(builder:flatbuffers.Builder, operationStatus:CoopEventInvitationOperationStatus) {
  builder.addFieldInt8(0, operationStatus, CoopEventInvitationOperationStatus.Ok);
}

static endSendTrainJourneyTeamInviteResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSendTrainJourneyTeamInviteResponse(builder:flatbuffers.Builder, operationStatus:CoopEventInvitationOperationStatus):flatbuffers.Offset {
  SendTrainJourneyTeamInviteResponse.startSendTrainJourneyTeamInviteResponse(builder);
  SendTrainJourneyTeamInviteResponse.addOperationStatus(builder, operationStatus);
  return SendTrainJourneyTeamInviteResponse.endSendTrainJourneyTeamInviteResponse(builder);
}
}
