// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ResponseStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/response-status-code.js';


export class SetProfileSettingResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetProfileSettingResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetProfileSettingResponse(bb:flatbuffers.ByteBuffer, obj?:SetProfileSettingResponse):SetProfileSettingResponse {
  return (obj || new SetProfileSettingResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetProfileSettingResponse(bb:flatbuffers.ByteBuffer, obj?:SetProfileSettingResponse):SetProfileSettingResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetProfileSettingResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

statusCode():ResponseStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponseStatusCode.Success;
}

static startSetProfileSettingResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addStatusCode(builder:flatbuffers.Builder, statusCode:ResponseStatusCode) {
  builder.addFieldInt8(0, statusCode, ResponseStatusCode.Success);
}

static endSetProfileSettingResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSetProfileSettingResponse(builder:flatbuffers.Builder, statusCode:ResponseStatusCode):flatbuffers.Offset {
  SetProfileSettingResponse.startSetProfileSettingResponse(builder);
  SetProfileSettingResponse.addStatusCode(builder, statusCode);
  return SetProfileSettingResponse.endSetProfileSettingResponse(builder);
}
}
