// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SpecialOfferEventInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SpecialOfferEventInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSpecialOfferEventInfo(bb:flatbuffers.ByteBuffer, obj?:SpecialOfferEventInfo):SpecialOfferEventInfo {
  return (obj || new SpecialOfferEventInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSpecialOfferEventInfo(bb:flatbuffers.ByteBuffer, obj?:SpecialOfferEventInfo):SpecialOfferEventInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SpecialOfferEventInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

remainingTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

configVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

config():string|null
config(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
config(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isSeasonal():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startSpecialOfferEventInfo(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addRemainingTime(builder:flatbuffers.Builder, remainingTime:bigint) {
  builder.addFieldInt64(1, remainingTime, BigInt('0'));
}

static addConfigVersion(builder:flatbuffers.Builder, configVersion:number) {
  builder.addFieldInt32(2, configVersion, 0);
}

static addConfig(builder:flatbuffers.Builder, configOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, configOffset, 0);
}

static addIsSeasonal(builder:flatbuffers.Builder, isSeasonal:boolean) {
  builder.addFieldInt8(4, +isSeasonal, +false);
}

static endSpecialOfferEventInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSpecialOfferEventInfo(builder:flatbuffers.Builder, id:number, remainingTime:bigint, configVersion:number, configOffset:flatbuffers.Offset, isSeasonal:boolean):flatbuffers.Offset {
  SpecialOfferEventInfo.startSpecialOfferEventInfo(builder);
  SpecialOfferEventInfo.addId(builder, id);
  SpecialOfferEventInfo.addRemainingTime(builder, remainingTime);
  SpecialOfferEventInfo.addConfigVersion(builder, configVersion);
  SpecialOfferEventInfo.addConfig(builder, configOffset);
  SpecialOfferEventInfo.addIsSeasonal(builder, isSeasonal);
  return SpecialOfferEventInfo.endSpecialOfferEventInfo(builder);
}
}
