// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum StageInfo {
  NONE = 0,
  NationalStageInfo = 1,
  GlobalStageInfo = 2
}
