// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { KnightType } from '../../../../../royal/infrastructure/services/backend/protocol/knight-type.js';
import { ProfileSetting } from '../../../../../royal/infrastructure/services/backend/protocol/profile-setting.js';
import { WorldCupBadge } from '../../../../../royal/infrastructure/services/backend/protocol/world-cup-badge.js';


export class TeamBattleUser {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TeamBattleUser {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTeamBattleUser(bb:flatbuffers.ByteBuffer, obj?:TeamBattleUser):TeamBattleUser {
  return (obj || new TeamBattleUser()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTeamBattleUser(bb:flatbuffers.ByteBuffer, obj?:TeamBattleUser):TeamBattleUser {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TeamBattleUser()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

userId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

score():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

lastUpdateDate():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

deprecatedIsGold():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

hasSpecialNameStyle():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

worldCupBadge(obj?:WorldCupBadge):WorldCupBadge|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new WorldCupBadge()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

profileSetting(obj?:ProfileSetting):ProfileSetting|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new ProfileSetting()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

knightType():KnightType {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : KnightType.None;
}

static startTeamBattleUser(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addUserId(builder:flatbuffers.Builder, userId:bigint) {
  builder.addFieldInt64(0, userId, BigInt('0'));
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addScore(builder:flatbuffers.Builder, score:number) {
  builder.addFieldInt32(2, score, 0);
}

static addLastUpdateDate(builder:flatbuffers.Builder, lastUpdateDate:bigint) {
  builder.addFieldInt64(3, lastUpdateDate, BigInt('0'));
}

static addDeprecatedIsGold(builder:flatbuffers.Builder, deprecatedIsGold:boolean) {
  builder.addFieldInt8(4, +deprecatedIsGold, +false);
}

static addHasSpecialNameStyle(builder:flatbuffers.Builder, hasSpecialNameStyle:boolean) {
  builder.addFieldInt8(5, +hasSpecialNameStyle, +false);
}

static addWorldCupBadge(builder:flatbuffers.Builder, worldCupBadgeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, worldCupBadgeOffset, 0);
}

static addProfileSetting(builder:flatbuffers.Builder, profileSettingOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, profileSettingOffset, 0);
}

static addKnightType(builder:flatbuffers.Builder, knightType:KnightType) {
  builder.addFieldInt8(8, knightType, KnightType.None);
}

static endTeamBattleUser(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
