// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ResponseStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/response-status-code.js';
import { TeamTreasureInfo } from '../../../../../royal/infrastructure/services/backend/protocol/team-treasure-info.js';


export class UpdateTeamTreasureResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UpdateTeamTreasureResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUpdateTeamTreasureResponse(bb:flatbuffers.ByteBuffer, obj?:UpdateTeamTreasureResponse):UpdateTeamTreasureResponse {
  return (obj || new UpdateTeamTreasureResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUpdateTeamTreasureResponse(bb:flatbuffers.ByteBuffer, obj?:UpdateTeamTreasureResponse):UpdateTeamTreasureResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UpdateTeamTreasureResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():ResponseStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponseStatusCode.Success;
}

teamTreasureInfo(obj?:TeamTreasureInfo):TeamTreasureInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new TeamTreasureInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startUpdateTeamTreasureResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addStatus(builder:flatbuffers.Builder, status:ResponseStatusCode) {
  builder.addFieldInt8(0, status, ResponseStatusCode.Success);
}

static addTeamTreasureInfo(builder:flatbuffers.Builder, teamTreasureInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, teamTreasureInfoOffset, 0);
}

static endUpdateTeamTreasureResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
