// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ResponseStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/response-status-code.js';


export class UpdateTeamMemberResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UpdateTeamMemberResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUpdateTeamMemberResponse(bb:flatbuffers.ByteBuffer, obj?:UpdateTeamMemberResponse):UpdateTeamMemberResponse {
  return (obj || new UpdateTeamMemberResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUpdateTeamMemberResponse(bb:flatbuffers.ByteBuffer, obj?:UpdateTeamMemberResponse):UpdateTeamMemberResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UpdateTeamMemberResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():ResponseStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponseStatusCode.Success;
}

static startUpdateTeamMemberResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addStatus(builder:flatbuffers.Builder, status:ResponseStatusCode) {
  builder.addFieldInt8(0, status, ResponseStatusCode.Success);
}

static endUpdateTeamMemberResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUpdateTeamMemberResponse(builder:flatbuffers.Builder, status:ResponseStatusCode):flatbuffers.Offset {
  UpdateTeamMemberResponse.startUpdateTeamMemberResponse(builder);
  UpdateTeamMemberResponse.addStatus(builder, status);
  return UpdateTeamMemberResponse.endUpdateTeamMemberResponse(builder);
}
}
