// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { WorldCupStage } from '../../../../../royal/infrastructure/services/backend/protocol/world-cup-stage.js';


export class UpdateWorldCupProgressRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UpdateWorldCupProgressRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUpdateWorldCupProgressRequest(bb:flatbuffers.ByteBuffer, obj?:UpdateWorldCupProgressRequest):UpdateWorldCupProgressRequest {
  return (obj || new UpdateWorldCupProgressRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUpdateWorldCupProgressRequest(bb:flatbuffers.ByteBuffer, obj?:UpdateWorldCupProgressRequest):UpdateWorldCupProgressRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UpdateWorldCupProgressRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

userEventId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

userStage():WorldCupStage {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : WorldCupStage.Upcoming;
}

userScore():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

country():string|null
country(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
country(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startUpdateWorldCupProgressRequest(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addUserEventId(builder:flatbuffers.Builder, userEventId:number) {
  builder.addFieldInt32(0, userEventId, 0);
}

static addUserStage(builder:flatbuffers.Builder, userStage:WorldCupStage) {
  builder.addFieldInt8(1, userStage, WorldCupStage.Upcoming);
}

static addUserScore(builder:flatbuffers.Builder, userScore:number) {
  builder.addFieldInt32(2, userScore, 0);
}

static addCountry(builder:flatbuffers.Builder, countryOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, countryOffset, 0);
}

static endUpdateWorldCupProgressRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUpdateWorldCupProgressRequest(builder:flatbuffers.Builder, userEventId:number, userStage:WorldCupStage, userScore:number, countryOffset:flatbuffers.Offset):flatbuffers.Offset {
  UpdateWorldCupProgressRequest.startUpdateWorldCupProgressRequest(builder);
  UpdateWorldCupProgressRequest.addUserEventId(builder, userEventId);
  UpdateWorldCupProgressRequest.addUserStage(builder, userStage);
  UpdateWorldCupProgressRequest.addUserScore(builder, userScore);
  UpdateWorldCupProgressRequest.addCountry(builder, countryOffset);
  return UpdateWorldCupProgressRequest.endUpdateWorldCupProgressRequest(builder);
}
}
