// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ClaimedEvents } from '../../../../../royal/infrastructure/services/backend/protocol/claimed-events.js';
import { DynamicOfferConfigVersions } from '../../../../../royal/infrastructure/services/backend/protocol/dynamic-offer-config-versions.js';
import { ForceData } from '../../../../../royal/infrastructure/services/backend/protocol/force-data.js';
import { UserProgressType, unionToUserProgressType, unionListToUserProgressType } from '../../../../../royal/infrastructure/services/backend/protocol/user-progress-type.js';
import { UserTeamTreasureState } from '../../../../../royal/infrastructure/services/backend/protocol/user-team-treasure-state.js';


export class UpdateUserProgressRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UpdateUserProgressRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUpdateUserProgressRequest(bb:flatbuffers.ByteBuffer, obj?:UpdateUserProgressRequest):UpdateUserProgressRequest {
  return (obj || new UpdateUserProgressRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUpdateUserProgressRequest(bb:flatbuffers.ByteBuffer, obj?:UpdateUserProgressRequest):UpdateUserProgressRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UpdateUserProgressRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

deviceId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

userProgressType(index: number):UserProgressType|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

userProgressTypeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

userProgressTypeArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

userProgress(index: number, obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb!.__vector(this.bb_pos + offset) + index * 4) : null;
}

userProgressLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

kingsCupGroupId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

teamId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

teamBattleGroupId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

madnessEventVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

forceData(obj?:ForceData):ForceData|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new ForceData()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

ladderOfferVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

royalPassVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

skyRaceGroupId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

specialOfferEventVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

pinataPartyVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

previousSyncedClientVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

teamTreasureEventId():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

teamTreasureConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

lightningRushGroupId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

spaceMissionGroupId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

spaceMissionConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

balloonRiseVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

weeklyLeaderboardJoinedEventId():number {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

hiddenTempleConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

teamGiftOfferConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

magicCauldronConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

claimedEvents(obj?:ClaimedEvents):ClaimedEvents|null {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? (obj || new ClaimedEvents()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

dragonNestConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

archeryArenaConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

dukesFortuneConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

eventDependencyConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 60);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

lavaQuestConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 62);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

dynamicOfferConfigVersions(obj?:DynamicOfferConfigVersions):DynamicOfferConfigVersions|null {
  const offset = this.bb!.__offset(this.bb_pos, 64);
  return offset ? (obj || new DynamicOfferConfigVersions()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

userTeamTreasureState(obj?:UserTeamTreasureState):UserTeamTreasureState|null {
  const offset = this.bb!.__offset(this.bb_pos, 66);
  return offset ? (obj || new UserTeamTreasureState()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

seasonalCardCollectionConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 68);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

teamTournamentConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 70);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

missionPursuitConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 72);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

seasonalCardPackOfferConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 74);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

missionControlConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 76);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

trainJourneyConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 78);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

oceanOdysseyConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 80);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

skyRaceConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 82);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

goldenOffersConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 84);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

dailyLightningRushConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 86);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

level():number {
  const offset = this.bb!.__offset(this.bb_pos, 88);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

puzzleBreakConfigVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 90);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

newRoyalPassVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 92);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startUpdateUserProgressRequest(builder:flatbuffers.Builder) {
  builder.startObject(45);
}

static addDeviceId(builder:flatbuffers.Builder, deviceId:number) {
  builder.addFieldInt32(0, deviceId, 0);
}

static addUserProgressType(builder:flatbuffers.Builder, userProgressTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, userProgressTypeOffset, 0);
}

static createUserProgressTypeVector(builder:flatbuffers.Builder, data:UserProgressType[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startUserProgressTypeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addUserProgress(builder:flatbuffers.Builder, userProgressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, userProgressOffset, 0);
}

static createUserProgressVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startUserProgressVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addKingsCupGroupId(builder:flatbuffers.Builder, kingsCupGroupId:bigint) {
  builder.addFieldInt64(3, kingsCupGroupId, BigInt('0'));
}

static addTeamId(builder:flatbuffers.Builder, teamId:bigint) {
  builder.addFieldInt64(4, teamId, BigInt('0'));
}

static addTeamBattleGroupId(builder:flatbuffers.Builder, teamBattleGroupId:bigint) {
  builder.addFieldInt64(5, teamBattleGroupId, BigInt('0'));
}

static addMadnessEventVersion(builder:flatbuffers.Builder, madnessEventVersion:number) {
  builder.addFieldInt32(6, madnessEventVersion, 0);
}

static addForceData(builder:flatbuffers.Builder, forceDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, forceDataOffset, 0);
}

static addLadderOfferVersion(builder:flatbuffers.Builder, ladderOfferVersion:number) {
  builder.addFieldInt32(8, ladderOfferVersion, 0);
}

static addRoyalPassVersion(builder:flatbuffers.Builder, royalPassVersion:number) {
  builder.addFieldInt32(9, royalPassVersion, 0);
}

static addSkyRaceGroupId(builder:flatbuffers.Builder, skyRaceGroupId:bigint) {
  builder.addFieldInt64(10, skyRaceGroupId, BigInt('0'));
}

static addSpecialOfferEventVersion(builder:flatbuffers.Builder, specialOfferEventVersion:number) {
  builder.addFieldInt32(11, specialOfferEventVersion, 0);
}

static addPinataPartyVersion(builder:flatbuffers.Builder, pinataPartyVersion:number) {
  builder.addFieldInt32(12, pinataPartyVersion, 0);
}

static addPreviousSyncedClientVersion(builder:flatbuffers.Builder, previousSyncedClientVersion:number) {
  builder.addFieldInt32(13, previousSyncedClientVersion, 0);
}

static addTeamTreasureEventId(builder:flatbuffers.Builder, teamTreasureEventId:number) {
  builder.addFieldInt32(14, teamTreasureEventId, 0);
}

static addTeamTreasureConfigVersion(builder:flatbuffers.Builder, teamTreasureConfigVersion:number) {
  builder.addFieldInt32(15, teamTreasureConfigVersion, 0);
}

static addLightningRushGroupId(builder:flatbuffers.Builder, lightningRushGroupId:bigint) {
  builder.addFieldInt64(16, lightningRushGroupId, BigInt('0'));
}

static addSpaceMissionGroupId(builder:flatbuffers.Builder, spaceMissionGroupId:bigint) {
  builder.addFieldInt64(17, spaceMissionGroupId, BigInt('0'));
}

static addSpaceMissionConfigVersion(builder:flatbuffers.Builder, spaceMissionConfigVersion:number) {
  builder.addFieldInt32(18, spaceMissionConfigVersion, 0);
}

static addBalloonRiseVersion(builder:flatbuffers.Builder, balloonRiseVersion:number) {
  builder.addFieldInt32(19, balloonRiseVersion, 0);
}

static addWeeklyLeaderboardJoinedEventId(builder:flatbuffers.Builder, weeklyLeaderboardJoinedEventId:number) {
  builder.addFieldInt32(20, weeklyLeaderboardJoinedEventId, 0);
}

static addHiddenTempleConfigVersion(builder:flatbuffers.Builder, hiddenTempleConfigVersion:number) {
  builder.addFieldInt32(21, hiddenTempleConfigVersion, 0);
}

static addTeamGiftOfferConfigVersion(builder:flatbuffers.Builder, teamGiftOfferConfigVersion:number) {
  builder.addFieldInt32(22, teamGiftOfferConfigVersion, 0);
}

static addMagicCauldronConfigVersion(builder:flatbuffers.Builder, magicCauldronConfigVersion:number) {
  builder.addFieldInt32(23, magicCauldronConfigVersion, 0);
}

static addClaimedEvents(builder:flatbuffers.Builder, claimedEventsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(24, claimedEventsOffset, 0);
}

static addDragonNestConfigVersion(builder:flatbuffers.Builder, dragonNestConfigVersion:number) {
  builder.addFieldInt32(25, dragonNestConfigVersion, 0);
}

static addArcheryArenaConfigVersion(builder:flatbuffers.Builder, archeryArenaConfigVersion:number) {
  builder.addFieldInt32(26, archeryArenaConfigVersion, 0);
}

static addDukesFortuneConfigVersion(builder:flatbuffers.Builder, dukesFortuneConfigVersion:number) {
  builder.addFieldInt32(27, dukesFortuneConfigVersion, 0);
}

static addEventDependencyConfigVersion(builder:flatbuffers.Builder, eventDependencyConfigVersion:number) {
  builder.addFieldInt32(28, eventDependencyConfigVersion, 0);
}

static addLavaQuestConfigVersion(builder:flatbuffers.Builder, lavaQuestConfigVersion:number) {
  builder.addFieldInt32(29, lavaQuestConfigVersion, 0);
}

static addDynamicOfferConfigVersions(builder:flatbuffers.Builder, dynamicOfferConfigVersionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(30, dynamicOfferConfigVersionsOffset, 0);
}

static addUserTeamTreasureState(builder:flatbuffers.Builder, userTeamTreasureStateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(31, userTeamTreasureStateOffset, 0);
}

static addSeasonalCardCollectionConfigVersion(builder:flatbuffers.Builder, seasonalCardCollectionConfigVersion:number) {
  builder.addFieldInt32(32, seasonalCardCollectionConfigVersion, 0);
}

static addTeamTournamentConfigVersion(builder:flatbuffers.Builder, teamTournamentConfigVersion:number) {
  builder.addFieldInt32(33, teamTournamentConfigVersion, 0);
}

static addMissionPursuitConfigVersion(builder:flatbuffers.Builder, missionPursuitConfigVersion:number) {
  builder.addFieldInt32(34, missionPursuitConfigVersion, 0);
}

static addSeasonalCardPackOfferConfigVersion(builder:flatbuffers.Builder, seasonalCardPackOfferConfigVersion:number) {
  builder.addFieldInt32(35, seasonalCardPackOfferConfigVersion, 0);
}

static addMissionControlConfigVersion(builder:flatbuffers.Builder, missionControlConfigVersion:number) {
  builder.addFieldInt32(36, missionControlConfigVersion, 0);
}

static addTrainJourneyConfigVersion(builder:flatbuffers.Builder, trainJourneyConfigVersion:number) {
  builder.addFieldInt32(37, trainJourneyConfigVersion, 0);
}

static addOceanOdysseyConfigVersion(builder:flatbuffers.Builder, oceanOdysseyConfigVersion:number) {
  builder.addFieldInt32(38, oceanOdysseyConfigVersion, 0);
}

static addSkyRaceConfigVersion(builder:flatbuffers.Builder, skyRaceConfigVersion:number) {
  builder.addFieldInt32(39, skyRaceConfigVersion, 0);
}

static addGoldenOffersConfigVersion(builder:flatbuffers.Builder, goldenOffersConfigVersion:number) {
  builder.addFieldInt32(40, goldenOffersConfigVersion, 0);
}

static addDailyLightningRushConfigVersion(builder:flatbuffers.Builder, dailyLightningRushConfigVersion:number) {
  builder.addFieldInt32(41, dailyLightningRushConfigVersion, 0);
}

static addLevel(builder:flatbuffers.Builder, level:number) {
  builder.addFieldInt32(42, level, 0);
}

static addPuzzleBreakConfigVersion(builder:flatbuffers.Builder, puzzleBreakConfigVersion:number) {
  builder.addFieldInt32(43, puzzleBreakConfigVersion, 0);
}

static addNewRoyalPassVersion(builder:flatbuffers.Builder, newRoyalPassVersion:number) {
  builder.addFieldInt32(44, newRoyalPassVersion, 0);
}

static endUpdateUserProgressRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
