// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class UserInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UserInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUserInfo(bb:flatbuffers.ByteBuffer, obj?:UserInfo):UserInfo {
  return (obj || new UserInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUserInfo(bb:flatbuffers.ByteBuffer, obj?:UserInfo):UserInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UserInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

userId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isGold():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

hasSpecialNameStyle():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isPremium():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startUserInfo(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addUserId(builder:flatbuffers.Builder, userId:bigint) {
  builder.addFieldInt64(0, userId, BigInt('0'));
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addIsGold(builder:flatbuffers.Builder, isGold:boolean) {
  builder.addFieldInt8(2, +isGold, +false);
}

static addHasSpecialNameStyle(builder:flatbuffers.Builder, hasSpecialNameStyle:boolean) {
  builder.addFieldInt8(3, +hasSpecialNameStyle, +false);
}

static addIsPremium(builder:flatbuffers.Builder, isPremium:boolean) {
  builder.addFieldInt8(4, +isPremium, +false);
}

static endUserInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUserInfo(builder:flatbuffers.Builder, userId:bigint, nameOffset:flatbuffers.Offset, isGold:boolean, hasSpecialNameStyle:boolean, isPremium:boolean):flatbuffers.Offset {
  UserInfo.startUserInfo(builder);
  UserInfo.addUserId(builder, userId);
  UserInfo.addName(builder, nameOffset);
  UserInfo.addIsGold(builder, isGold);
  UserInfo.addHasSpecialNameStyle(builder, hasSpecialNameStyle);
  UserInfo.addIsPremium(builder, isPremium);
  return UserInfo.endUserInfo(builder);
}
}
