// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { OTPFailReason } from '../../../../../royal/infrastructure/services/backend/protocol/otpfail-reason.js';
import { ResponseStatusCode } from '../../../../../royal/infrastructure/services/backend/protocol/response-status-code.js';


export class VerifyOTPResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VerifyOTPResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVerifyOTPResponse(bb:flatbuffers.ByteBuffer, obj?:VerifyOTPResponse):VerifyOTPResponse {
  return (obj || new VerifyOTPResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVerifyOTPResponse(bb:flatbuffers.ByteBuffer, obj?:VerifyOTPResponse):VerifyOTPResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VerifyOTPResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():ResponseStatusCode {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponseStatusCode.Success;
}

reason():OTPFailReason {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : OTPFailReason.None;
}

static startVerifyOTPResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addStatus(builder:flatbuffers.Builder, status:ResponseStatusCode) {
  builder.addFieldInt8(0, status, ResponseStatusCode.Success);
}

static addReason(builder:flatbuffers.Builder, reason:OTPFailReason) {
  builder.addFieldInt8(1, reason, OTPFailReason.None);
}

static endVerifyOTPResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVerifyOTPResponse(builder:flatbuffers.Builder, status:ResponseStatusCode, reason:OTPFailReason):flatbuffers.Offset {
  VerifyOTPResponse.startVerifyOTPResponse(builder);
  VerifyOTPResponse.addStatus(builder, status);
  VerifyOTPResponse.addReason(builder, reason);
  return VerifyOTPResponse.endVerifyOTPResponse(builder);
}
}
