// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum WorldCupStage {
  Upcoming = 0,
  National = 1,
  Global = 2,
  Result = 3
}
