// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum WorldCupBadgeType {
  None = 0,
  Standard = 1,
  Bronze = 2,
  Silver = 3,
  Gold = 4
}
